---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
    register: result

  - name: Delete instances
    cloud: ospcloud
      name: "{{ item.name }}"
      state: absent
    loop: "{{ result.ansible_facts.openstack_servers }}"
   
